disabled-roles:
  archer: false
  assassin: false
  healer: false
  mage: false
  tank: false
players:
  min: 2
  max: 12
timers:
  lobby: 30
  between-waves: 15
sql:
  use: false
  ip: localhost
  port: 3306
  username: root
  password: 
  database: minecraft
